services:
  nginx:
    image: nginx:alpine
    container_name: procrastination-killer
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro